
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
server:
  port: 8087
spring:
  application:
    name: notifications-service
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configtree:/mnt/secrets/ccpay/"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notifications
    username: notifications
    password: notifications
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${ISSUER_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        # Dummy OIDC client required even we are not going to use
        registration:
          oidc:
            client-id: ${OIDC_CLIENT_ID:paybubble}
            client-secret: ${OIDC_CLIENT_SECRET}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true

security:
  anonymousPaths:
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/search/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000

trusted:
  s2s:
    service:
      names: refunds_api,ccpay_bubble,xui_webapp
auth:
  idam:
    client:
      baseUrl: ${AUTH_IDAM_CLIENT_BASEURL}
  provider:
    service:
      client:
        baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
oidc:
  audience-list: ${OIDC_AUDIENCE_LIST:refunds_api}
  issuer: ${OIDC_ISSUER:https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts}

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}


notify:
  letter.apiKey: ${LETTER_APIKEY:testingnotification-ff5a9c4f-efd8-4553-9c18-80ab45d578ce-b00802b8-ef78-4be4-bb60-12530cff3d80}
  letter.template:
  email.apiKey: ${EMAIL_APIKEY:notificationtestkey-ff5a9c4f-efd8-4553-9c18-80ab45d578ce-0fcc72db-0c9b-4262-af43-c16f1da47037}
  email.template:
  template:
    cheque-po-cash:
      letter: ${NOTIFICATIONS_LETTER_CHEQUE_PO_CASH_TEMPLATE_ID:}
      email: ${NOTIFICATIONS_EMAIL_CHEQUE_PO_CASH_TEMPLATE_ID:}
    card-pba:
      letter: ${NOTIFICATION_LETTER_CARD_PBA_TEMPLATE_ID:}
      email: ${NOTIFICATION_EMAIL_CARD_PBA_TEMPLATE_ID:}
    from-details:
      email: HM Courts and Tribunals Registrations <hm.courts.and.tribunals.registrations@notifications.service.gov.uk>
      mail:
        address-line: ABC
        county: london
        country: UK
        city: london
        post-code: 123 436

idam:
  api:
    url: ${IDAM_API_URL:https://idam-api.aat.platform.hmcts.net}
  s2s-authorised:
    services: ${S2S_AUTHORISED_SERVICES:refunds_api,ccpay_bubble,xui_webapp}
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    totp_secret: ${OIDC_S2S_SECRET}
    microservice: ${OIDC_S2S_MICROSERVICE_NAME:notifications_service}
