apiVersion: v2
appVersion: "1.0"
description: A Helm chart for notifications-service App
name: ccpay-notifications-service
home: https://github.com/hmcts/ccpay-notifications-service
version: 0.0.9
maintainers:
  - name: HMCTS Fees and Pay team
dependencies:
  - name: java
    version: 4.0.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
