java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/ccpay/notifications-service:latest'
  ingressHost: notifications-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: ccpay-notifications-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: notifications
    POSTGRES_USERNAME: notifications@ccpay-notifications-service-postgres-db-v11-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    ISSUER_URI: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o"
    OIDC_CLIENT_ID: "paybubble"
    OIDC_ISSUER: "https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts"
    OIDC_S2S_MICROSERVICE_NAME: notifications_service
    OIDC_AUDIENCE_LIST: refunds_api
    S2S_AUTHORISED_SERVICES: refunds_api
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    LAUNCH_DARKLY_USER_NAME_PREFIX: '{{ .Values.global.environment }}'
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: notifications-service-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key


