java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/ccpay/notifications-service:latest'
  ingressHost: notifications-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: notifications-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: notifications
    POSTGRES_USERNAME: notifications@notifications-service-postgres-db-v11-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    ISSUER_URI: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o"
    OIDC_CLIENT_ID: "paybubble"
    OIDC_ISSUER: "https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts"
    OIDC_S2S_MICROSERVICE_NAME: notifications_service
    OIDC_AUDIENCE_LIST: refunds_api
    S2S_AUTHORISED_SERVICES: refunds_api
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    LAUNCH_DARKLY_USER_NAME_PREFIX: '{{ .Values.global.environment }}'
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: notifications-service-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key

#    PAYMENT_API_URL: "http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
#    LIBERATA_OAUTH2_AUTHORIZE_URL: "https://bpacustomerportal.liberata.com/pba/public/oauth/authorize"
#    LIBERATA_OAUTH2_TOKEN_URL: "https://bpacustomerportal.liberata.com/pba/public/oauth/token"
#    LIBERATA_BASE_URL: "https://bpacustomerportal.liberata.com"
#    REFUND_STATUS_UPDATE_PATH: "/refunds-api/refund"
#    USER_INFO_SIZE: 300
#    USER_LAST_MODIFIED_TIME: 720d
#    REFUND_SERVICE_ACCOUNT_CLIENT_ID: "refunds_api"
#    REFUND_SERVICE_ACCOUNT_GRANT_TYPE: "password"
#    REFUND_SERVICE_ACCOUNT_USERNAME: "idam.user.ccpayrefundsapi@hmcts.net"
#    REFUND_SERVICE_ACCOUNT_SCOPE: "openid profile roles search-user"
#    REFUND_SERVICE_ACCOUNT_REDIRECT_URI: "http://ccpay-refunds-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    rpe:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
#  environment:


